// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fields_player.proto

package pbtest

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoveragePlayerEnum int32

const (
	CoveragePlayerEnum_CoveragePlayerEnum_None  CoveragePlayerEnum = 0
	CoveragePlayerEnum_CoveragePlayerEnum_Test1 CoveragePlayerEnum = 1
	CoveragePlayerEnum_CoveragePlayerEnum_Test2 CoveragePlayerEnum = 2
)

// Enum value maps for CoveragePlayerEnum.
var (
	CoveragePlayerEnum_name = map[int32]string{
		0: "CoveragePlayerEnum_None",
		1: "CoveragePlayerEnum_Test1",
		2: "CoveragePlayerEnum_Test2",
	}
	CoveragePlayerEnum_value = map[string]int32{
		"CoveragePlayerEnum_None":  0,
		"CoveragePlayerEnum_Test1": 1,
		"CoveragePlayerEnum_Test2": 2,
	}
)

func (x CoveragePlayerEnum) Enum() *CoveragePlayerEnum {
	p := new(CoveragePlayerEnum)
	*p = x
	return p
}

func (x CoveragePlayerEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoveragePlayerEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_fields_player_proto_enumTypes[0].Descriptor()
}

func (CoveragePlayerEnum) Type() protoreflect.EnumType {
	return &file_fields_player_proto_enumTypes[0]
}

func (x CoveragePlayerEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoveragePlayerEnum.Descriptor instead.
func (CoveragePlayerEnum) EnumDescriptor() ([]byte, []int) {
	return file_fields_player_proto_rawDescGZIP(), []int{0}
}

type FieldsHero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid           int32                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	HeroLevel     int32                  `protobuf:"varint,3,opt,name=hero_level,json=heroLevel,proto3" json:"hero_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsHero) Reset() {
	*x = FieldsHero{}
	mi := &file_fields_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsHero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsHero) ProtoMessage() {}

func (x *FieldsHero) ProtoReflect() protoreflect.Message {
	mi := &file_fields_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsHero.ProtoReflect.Descriptor instead.
func (*FieldsHero) Descriptor() ([]byte, []int) {
	return file_fields_player_proto_rawDescGZIP(), []int{0}
}

func (x *FieldsHero) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FieldsHero) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *FieldsHero) GetHeroLevel() int32 {
	if x != nil {
		return x.HeroLevel
	}
	return 0
}

type FieldsBaseModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsBaseModel) Reset() {
	*x = FieldsBaseModel{}
	mi := &file_fields_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsBaseModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsBaseModel) ProtoMessage() {}

func (x *FieldsBaseModel) ProtoReflect() protoreflect.Message {
	mi := &file_fields_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsBaseModel.ProtoReflect.Descriptor instead.
func (*FieldsBaseModel) Descriptor() ([]byte, []int) {
	return file_fields_player_proto_rawDescGZIP(), []int{1}
}

func (x *FieldsBaseModel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FieldsBaseModel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// FIELDS 模式 + blob/json + skip_set_default（EX-SC-001/003/004）。
type FieldsPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Heros         []*FieldsHero          `protobuf:"bytes,5,rep,name=heros,proto3" json:"heros,omitempty"`
	Settings      map[string]int32       `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PlayerEnum    CoveragePlayerEnum     `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3,enum=pbtest.CoveragePlayerEnum" json:"player_enum,omitempty"`
	SkipMe        *FieldsBaseModel       `protobuf:"bytes,10,opt,name=skip_me,json=skipMe,proto3" json:"skip_me,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsPlayer) Reset() {
	*x = FieldsPlayer{}
	mi := &file_fields_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsPlayer) ProtoMessage() {}

func (x *FieldsPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_fields_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsPlayer.ProtoReflect.Descriptor instead.
func (*FieldsPlayer) Descriptor() ([]byte, []int) {
	return file_fields_player_proto_rawDescGZIP(), []int{2}
}

func (x *FieldsPlayer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FieldsPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldsPlayer) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FieldsPlayer) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *FieldsPlayer) GetHeros() []*FieldsHero {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *FieldsPlayer) GetSettings() map[string]int32 {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *FieldsPlayer) GetPlayerEnum() CoveragePlayerEnum {
	if x != nil {
		return x.PlayerEnum
	}
	return CoveragePlayerEnum_CoveragePlayerEnum_None
}

func (x *FieldsPlayer) GetSkipMe() *FieldsBaseModel {
	if x != nil {
		return x.SkipMe
	}
	return nil
}

var File_fields_player_proto protoreflect.FileDescriptor

const file_fields_player_proto_rawDesc = "" +
	"\n" +
	"\x13fields_player.proto\x12\x06pbtest\x1a\x10orm.option.proto\"M\n" +
	"\n" +
	"FieldsHero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x05R\x03cid\x12\x1d\n" +
	"\n" +
	"hero_level\x18\x03 \x01(\x05R\theroLevel\"\xb3\x01\n" +
	"\x0fFieldsBaseModel\x12T\n" +
	"\n" +
	"created_at\x18\x01 \x01(\x03B5\x9a\x84\x9e\x030gorm:\"autoCreateTime;<-:create\" json:\"createdAt\"R\tcreatedAt\x12J\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03B+\x9a\x84\x9e\x03&gorm:\"autoUpdateTime\" json:\"updatedAt\"R\tupdatedAt\"\xb4\x03\n" +
	"\fFieldsPlayer\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xa0\x84\x9e\x03\x01R\x02id\x12\x19\n" +
	"\x04name\x18\x02 \x01(\tB\x05\xb0\x84\x9e\x03\x01R\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12?\n" +
	"\x05heros\x18\x05 \x03(\v2\x12.pbtest.FieldsHeroB\x15\x9a\x84\x9e\x03\x10gorm:\"type:blob\"R\x05heros\x12>\n" +
	"\bsettings\x18\a \x03(\v2\".pbtest.FieldsPlayer.SettingsEntryR\bsettings\x12;\n" +
	"\vplayer_enum\x18\t \x01(\x0e2\x1a.pbtest.CoveragePlayerEnumR\n" +
	"playerEnum\x12=\n" +
	"\askip_me\x18\n" +
	" \x01(\v2\x17.pbtest.FieldsBaseModelB\v\x9a\x84\x9e\x03\x01-\xa8\x84\x9e\x03\x01R\x06skipMe\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01:\x10\xf0\xa7\x1d\x01\xfa\xa7\x1d\x04game\x80\xa8\x1d\x01*m\n" +
	"\x12CoveragePlayerEnum\x12\x1b\n" +
	"\x17CoveragePlayerEnum_None\x10\x00\x12\x1c\n" +
	"\x18CoveragePlayerEnum_Test1\x10\x01\x12\x1c\n" +
	"\x18CoveragePlayerEnum_Test2\x10\x02B\vZ\tgs/pbtestb\x06proto3"

var (
	file_fields_player_proto_rawDescOnce sync.Once
	file_fields_player_proto_rawDescData []byte
)

func file_fields_player_proto_rawDescGZIP() []byte {
	file_fields_player_proto_rawDescOnce.Do(func() {
		file_fields_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fields_player_proto_rawDesc), len(file_fields_player_proto_rawDesc)))
	})
	return file_fields_player_proto_rawDescData
}

var file_fields_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fields_player_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fields_player_proto_goTypes = []any{
	(CoveragePlayerEnum)(0), // 0: pbtest.CoveragePlayerEnum
	(*FieldsHero)(nil),      // 1: pbtest.FieldsHero
	(*FieldsBaseModel)(nil), // 2: pbtest.FieldsBaseModel
	(*FieldsPlayer)(nil),    // 3: pbtest.FieldsPlayer
	nil,                     // 4: pbtest.FieldsPlayer.SettingsEntry
}
var file_fields_player_proto_depIdxs = []int32{
	1, // 0: pbtest.FieldsPlayer.heros:type_name -> pbtest.FieldsHero
	4, // 1: pbtest.FieldsPlayer.settings:type_name -> pbtest.FieldsPlayer.SettingsEntry
	0, // 2: pbtest.FieldsPlayer.player_enum:type_name -> pbtest.CoveragePlayerEnum
	2, // 3: pbtest.FieldsPlayer.skip_me:type_name -> pbtest.FieldsBaseModel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_fields_player_proto_init() }
func file_fields_player_proto_init() {
	if File_fields_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fields_player_proto_rawDesc), len(file_fields_player_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fields_player_proto_goTypes,
		DependencyIndexes: file_fields_player_proto_depIdxs,
		EnumInfos:         file_fields_player_proto_enumTypes,
		MessageInfos:      file_fields_player_proto_msgTypes,
	}.Build()
	File_fields_player_proto = out.File
	file_fields_player_proto_goTypes = nil
	file_fields_player_proto_depIdxs = nil
}
