// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: tables.proto
// time 2026-06-06

package pbtest

import (
	proto "google.golang.org/protobuf/proto"
)

// GetPlayerTable 转换actor state为Player类型
func GetPlayerTable(holder interface{ GetStateValue() proto.Message }) *Player {
	return holder.GetStateValue().(*Player)
}

// ShardingKey 供 go-orm 分片路由（orm.ShardingKeyProvider）
func (x *Player) ShardingKey() int64 {
	return x.Id
}

func SetPlayerDefaults(r *Player) {
	if r == nil {
		return
	}
	if r.BaseInfo == nil {
		r.BaseInfo = &RoleBaseInfo{}
		SetRoleBaseInfoDefaults(r.BaseInfo)
	}
	if r.ItemInfo == nil {
		r.ItemInfo = &ItemInfo{}
		SetItemInfoDefaults(r.ItemInfo)
	}
	if r.AfkEarnings == nil {
		r.AfkEarnings = &AfkEarnings{}
		SetAfkEarningsDefaults(r.AfkEarnings)
	}
	if r.BattleLevelInfo == nil {
		r.BattleLevelInfo = &BattleLevelInfo{}
		SetBattleLevelInfoDefaults(r.BattleLevelInfo)
	}
	if r.EquipmentInfo == nil {
		r.EquipmentInfo = &EquipmentInfo{}
		SetEquipmentInfoDefaults(r.EquipmentInfo)
	}
	if r.SkillInfo == nil {
		r.SkillInfo = &SkillInfo{}
		SetSkillInfoDefaults(r.SkillInfo)
	}
	if r.GemInfo == nil {
		r.GemInfo = &GemInfo{}
		SetGemInfoDefaults(r.GemInfo)
	}
	if r.FuncOpen == nil {
		r.FuncOpen = &FuncOpen{}
		SetFuncOpenDefaults(r.FuncOpen)
	}
	if r.ShopGoodsInfo == nil {
		r.ShopGoodsInfo = &ShopGoodsInfo{}
		SetShopGoodsInfoDefaults(r.ShopGoodsInfo)
	}
	if r.PaymentOrderInfo == nil {
		r.PaymentOrderInfo = &PaymentOrderInfo{}
		SetPaymentOrderInfoDefaults(r.PaymentOrderInfo)
	}
	if r.TaskInfo == nil {
		r.TaskInfo = &TaskInfo{}
		SetTaskInfoDefaults(r.TaskInfo)
	}
	if r.MailInfo == nil {
		r.MailInfo = &MailInfo{}
		SetMailInfoDefaults(r.MailInfo)
	}
	if r.UavInfo == nil {
		r.UavInfo = &UavInfo{}
		SetUavInfoDefaults(r.UavInfo)
	}
	if r.WeaponInfo == nil {
		r.WeaponInfo = &WeaponInfo{}
		SetWeaponInfoDefaults(r.WeaponInfo)
	}
	if r.LogInfo == nil {
		r.LogInfo = &LogInfo{}
		SetLogInfoDefaults(r.LogInfo)
	}
	if r.FeedbackLogInfo == nil {
		r.FeedbackLogInfo = &FeedbackLogInfo{}
		SetFeedbackLogInfoDefaults(r.FeedbackLogInfo)
	}
	if r.FashionInfo == nil {
		r.FashionInfo = &FashionInfo{}
		SetFashionInfoDefaults(r.FashionInfo)
	}
	if r.Badge_Info == nil {
		r.Badge_Info = &BadgeInfo{}
		SetBadgeInfoDefaults(r.Badge_Info)
	}
	if r.MonsterCollect == nil {
		r.MonsterCollect = &MonsterCollect{}
		SetMonsterCollectDefaults(r.MonsterCollect)
	}
	if r.RoleOpRecord == nil {
		r.RoleOpRecord = &RoleOpRecord{}
		SetRoleOpRecordDefaults(r.RoleOpRecord)
	}
	if r.RenovationLaboratory == nil {
		r.RenovationLaboratory = &RenovationLaboratory{}
		SetRenovationLaboratoryDefaults(r.RenovationLaboratory)
	}
	if r.BattlePass == nil {
		r.BattlePass = &BattlePass{}
		SetBattlePassDefaults(r.BattlePass)
	}
	if r.MttCbtTicketReward == nil {
		r.MttCbtTicketReward = &MttCbtTicketReward{}
		SetMttCbtTicketRewardDefaults(r.MttCbtTicketReward)
	}
	if r.ActivityInfo == nil {
		r.ActivityInfo = &ActivityInfo{}
		SetActivityInfoDefaults(r.ActivityInfo)
	}
	if r.AntiCheatingInfo == nil {
		r.AntiCheatingInfo = &AntiCheatingInfo{}
		SetAntiCheatingInfoDefaults(r.AntiCheatingInfo)
	}

}

func SetItemDefaults(r *Item) {
	if r == nil {
		return
	}

}

func SetRewardItemDefaults(r *RewardItem) {
	if r == nil {
		return
	}

}

func SetRoleItemChangeDtoDefaults(r *RoleItemChangeDto) {
	if r == nil {
		return
	}
	if r.EquipSnapshot == nil {
		r.EquipSnapshot = &EquipSnapshot{}
		SetEquipSnapshotDefaults(r.EquipSnapshot)
	}

}

func SetEquipAttrDefaults(r *EquipAttr) {
	if r == nil {
		return
	}

}

func SetEquipAttrSnapshotDefaults(r *EquipAttrSnapshot) {
	if r == nil {
		return
	}

}

func SetEquipSnapshotDefaults(r *EquipSnapshot) {
	if r == nil {
		return
	}
	if r.Attrs == nil {
		r.Attrs = make([]*EquipAttrSnapshot, 0)
	}

}

func SetEnhanceInfoDefaults(r *EnhanceInfo) {
	if r == nil {
		return
	}
	if r.EnhanceCid == nil {
		r.EnhanceCid = make([]int32, 0)
	}

}

func SetEquipmentDefaults(r *Equipment) {
	if r == nil {
		return
	}
	if r.EquipAttr == nil {
		r.EquipAttr = make([]*EquipAttr, 0)
	}

}

func SetEquipmentInfoDefaults(r *EquipmentInfo) {
	if r == nil {
		return
	}
	if r.Equipment == nil {
		r.Equipment = make(map[int64]*Equipment)
	}
	if r.EnhanceInfo == nil {
		r.EnhanceInfo = &EnhanceInfo{}
		SetEnhanceInfoDefaults(r.EnhanceInfo)
	}

}

func SetGemSlotListDefaults(r *GemSlotList) {
	if r == nil {
		return
	}
	if r.GemCidList == nil {
		r.GemCidList = make([]int32, 0)
	}

}

func SetGemPresetInfosDefaults(r *GemPresetInfos) {
	if r == nil {
		return
	}
	if r.SlotList == nil {
		r.SlotList = make([]*GemSlotList, 0)
	}

}

func SetGemSlotDefaults(r *GemSlot) {
	if r == nil {
		return
	}
	if r.GemInfos == nil {
		r.GemInfos = make([]*GemPresetInfos, 0)
	}

}

func SetGemLockDefaults(r *GemLock) {
	if r == nil {
		return
	}

}

func SetGemInfoDefaults(r *GemInfo) {
	if r == nil {
		return
	}
	if r.GemSlot == nil {
		r.GemSlot = &GemSlot{}
		SetGemSlotDefaults(r.GemSlot)
	}
	if r.GemLock == nil {
		r.GemLock = make([]*GemLock, 0)
	}

}

func SetFashionDefaults(r *Fashion) {
	if r == nil {
		return
	}

}

func SetFashionSlotSkillListDefaults(r *FashionSlotSkillList) {
	if r == nil {
		return
	}
	if r.SkillIds == nil {
		r.SkillIds = make([]int32, 0)
	}

}

func SetFashionSkillTabInfoDefaults(r *FashionSkillTabInfo) {
	if r == nil {
		return
	}
	if r.SlotList == nil {
		r.SlotList = make([]*FashionSlotSkillList, 0)
	}

}

func SetFashionSkillTabInfosDefaults(r *FashionSkillTabInfos) {
	if r == nil {
		return
	}
	if r.SkillTabInfos == nil {
		r.SkillTabInfos = make([]*FashionSkillTabInfo, 0)
	}

}

func SetFashionSkillSlotDefaults(r *FashionSkillSlot) {
	if r == nil {
		return
	}
	if r.FashionSkillInfos == nil {
		r.FashionSkillInfos = &FashionSkillTabInfos{}
		SetFashionSkillTabInfosDefaults(r.FashionSkillInfos)
	}

}

func SetFashionInfoDefaults(r *FashionInfo) {
	if r == nil {
		return
	}
	if r.Fashion == nil {
		r.Fashion = make(map[int32]*Fashion)
	}
	if r.FashionSkillSlot == nil {
		r.FashionSkillSlot = &FashionSkillSlot{}
		SetFashionSkillSlotDefaults(r.FashionSkillSlot)
	}

}

func SetSkillDefaults(r *Skill) {
	if r == nil {
		return
	}

}

func SetActiveSkillDefaults(r *ActiveSkill) {
	if r == nil {
		return
	}

}

func SetActSkillInfosDefaults(r *ActSkillInfos) {
	if r == nil {
		return
	}
	if r.SkillInfo == nil {
		r.SkillInfo = make([]int32, 0)
	}

}

func SetActiveSkillSlotDefaults(r *ActiveSkillSlot) {
	if r == nil {
		return
	}
	if r.ActSkillInfos == nil {
		r.ActSkillInfos = make([]*ActSkillInfos, 0)
	}

}

func SetSkillInfoDefaults(r *SkillInfo) {
	if r == nil {
		return
	}
	if r.Skill == nil {
		r.Skill = make([]*Skill, 0)
	}
	if r.ActiveSkill == nil {
		r.ActiveSkill = make([]*ActiveSkill, 0)
	}
	if r.ActiveSkillSlot == nil {
		r.ActiveSkillSlot = &ActiveSkillSlot{}
		SetActiveSkillSlotDefaults(r.ActiveSkillSlot)
	}

}

func SetCombatingDefaults(r *Combating) {
	if r == nil {
		return
	}

}

func SetCombatLevelDefaults(r *CombatLevel) {
	if r == nil {
		return
	}

}

func SetCombatRewardDefaults(r *CombatReward) {
	if r == nil {
		return
	}
	if r.GotScoreList == nil {
		r.GotScoreList = make([]int32, 0)
	}

}

func SetCombatSweepDefaults(r *CombatSweep) {
	if r == nil {
		return
	}

}

func SetCombatLogDefaults(r *CombatLog) {
	if r == nil {
		return
	}
	if r.Rewards == nil {
		r.Rewards = make([]*RewardItem, 0)
	}
	if r.SkillChoices == nil {
		r.SkillChoices = make([]int32, 0)
	}
	if r.KilledEnemies == nil {
		r.KilledEnemies = make([]*CombatLog_Enemy, 0)
	}

}

// nested messages
func SetCombatLog_EnemyDefaults(r *CombatLog_Enemy) {
	if r == nil {
		return
	}

}

func SetCombatLevelFirstCompleteRewardRecordDefaults(r *CombatLevelFirstCompleteRewardRecord) {
	if r == nil {
		return
	}
	if r.Cid == nil {
		r.Cid = make([]int32, 0)
	}

}

func SetBattleLevelInfoDefaults(r *BattleLevelInfo) {
	if r == nil {
		return
	}
	if r.Combating == nil {
		r.Combating = &Combating{}
		SetCombatingDefaults(r.Combating)
	}
	if r.CombatLevel == nil {
		r.CombatLevel = make(map[int32]*CombatLevel)
	}
	if r.CombatReward == nil {
		r.CombatReward = make(map[int32]*CombatReward)
	}
	if r.CombatSweep == nil {
		r.CombatSweep = make([]*CombatSweep, 0)
	}
	if r.CombatLog == nil {
		r.CombatLog = make(map[string]*CombatLog)
	}
	if r.CombatLevelFirstCompleteRewardRecord == nil {
		r.CombatLevelFirstCompleteRewardRecord = &CombatLevelFirstCompleteRewardRecord{}
		SetCombatLevelFirstCompleteRewardRecordDefaults(r.CombatLevelFirstCompleteRewardRecord)
	}

}

func SetTaskDefaults(r *Task) {
	if r == nil {
		return
	}
	if r.RewardSlice == nil {
		r.RewardSlice = make([]int32, 0)
	}

}

func SetTaskInfoDefaults(r *TaskInfo) {
	if r == nil {
		return
	}
	if r.Task == nil {
		r.Task = make([]*Task, 0)
	}

}

func SetPaymentOrderDefaults(r *PaymentOrder) {
	if r == nil {
		return
	}
	if r.Rewards == nil {
		r.Rewards = make([]*RoleItemChangeDto, 0)
	}

}

func SetPaymentOrderInfoDefaults(r *PaymentOrderInfo) {
	if r == nil {
		return
	}
	if r.PaymentOrder == nil {
		r.PaymentOrder = make(map[int64]*PaymentOrder)
	}

}

func SetShopGoodsPurchaseLogDefaults(r *ShopGoodsPurchaseLog) {
	if r == nil {
		return
	}

}

func SetStorageGoodsDefaults(r *StorageGoods) {
	if r == nil {
		return
	}

}

func SetDiamondShopGoodsPurchaseLogDefaults(r *DiamondShopGoodsPurchaseLog) {
	if r == nil {
		return
	}

}

func SetGiftPurchaseLogDefaults(r *GiftPurchaseLog) {
	if r == nil {
		return
	}
	if r.RewardStatus == nil {
		r.RewardStatus = make([]bool, 0)
	}

}

func SetShopGoodsInfoDefaults(r *ShopGoodsInfo) {
	if r == nil {
		return
	}
	if r.ShopGoodsPurchaseLog == nil {
		r.ShopGoodsPurchaseLog = make([]*ShopGoodsPurchaseLog, 0)
	}
	if r.StorageGoods == nil {
		r.StorageGoods = make(map[int32]*StorageGoods)
	}
	if r.DiamondShopGoodsPurchaseLog == nil {
		r.DiamondShopGoodsPurchaseLog = make([]*DiamondShopGoodsPurchaseLog, 0)
	}
	if r.GiftPurchaseLog == nil {
		r.GiftPurchaseLog = make([]*GiftPurchaseLog, 0)
	}

}

func SetDrawGachaLogDefaults(r *DrawGachaLog) {
	if r == nil {
		return
	}

}

func SetLotteryHoroscopeDefaults(r *LotteryHoroscope) {
	if r == nil {
		return
	}
	if r.BeenDrawnList == nil {
		r.BeenDrawnList = make([]*LotteryHoroscope_DrawnList, 0)
	}

}

// nested messages
func SetLotteryHoroscope_DrawnListDefaults(r *LotteryHoroscope_DrawnList) {
	if r == nil {
		return
	}
	if r.RewardList == nil {
		r.RewardList = make([]int32, 0)
	}

}

func SetLuckyDrawDefaults(r *LuckyDraw) {
	if r == nil {
		return
	}
	if r.DrawCountRewardRecords == nil {
		r.DrawCountRewardRecords = make([]int32, 0)
	}

}

func SetGradedFundDefaults(r *GradedFund) {
	if r == nil {
		return
	}
	if r.GotStatus == nil {
		r.GotStatus = make(map[int32]int32)
	}

}

func SetLevelGiftDefaults(r *LevelGift) {
	if r == nil {
		return
	}
	if r.PurchaseRecord == nil {
		r.PurchaseRecord = make(map[int32]int32)
	}

}

func SetDailyRechargeRewardGotStatusDefaults(r *DailyRechargeRewardGotStatus) {
	if r == nil {
		return
	}
	if r.AccumulativeDaysGotList == nil {
		r.AccumulativeDaysGotList = make([]int32, 0)
	}
	if r.DiamondLevelGetStatus == nil {
		r.DiamondLevelGetStatus = make(map[int32]int32)
	}

}

func SetDailyRechargeDefaults(r *DailyRecharge) {
	if r == nil {
		return
	}
	if r.RewardStatus == nil {
		r.RewardStatus = make(map[int32]*DailyRechargeRewardGotStatus)
	}

}

func SetCumulativeRechargeDefaults(r *CumulativeRecharge) {
	if r == nil {
		return
	}
	if r.GotList == nil {
		r.GotList = make([]int32, 0)
	}

}

func SetActivityInfoDefaults(r *ActivityInfo) {
	if r == nil {
		return
	}
	if r.LotteryHoroscope == nil {
		r.LotteryHoroscope = &LotteryHoroscope{}
		SetLotteryHoroscopeDefaults(r.LotteryHoroscope)
	}
	if r.LuckyDraw == nil {
		r.LuckyDraw = &LuckyDraw{}
		SetLuckyDrawDefaults(r.LuckyDraw)
	}
	if r.GradedFund == nil {
		r.GradedFund = &GradedFund{}
		SetGradedFundDefaults(r.GradedFund)
	}
	if r.DailyRecharge == nil {
		r.DailyRecharge = &DailyRecharge{}
		SetDailyRechargeDefaults(r.DailyRecharge)
	}
	if r.LevelGift == nil {
		r.LevelGift = &LevelGift{}
		SetLevelGiftDefaults(r.LevelGift)
	}
	if r.CumulativeRecharge == nil {
		r.CumulativeRecharge = &CumulativeRecharge{}
		SetCumulativeRechargeDefaults(r.CumulativeRecharge)
	}

}

func SetMailDefaults(r *Mail) {
	if r == nil {
		return
	}
	if r.Attachments == nil {
		r.Attachments = make([]*RewardItem, 0)
	}

}

func SetMailLogDefaults(r *MailLog) {
	if r == nil {
		return
	}

}

func SetMailInfoDefaults(r *MailInfo) {
	if r == nil {
		return
	}
	if r.Mail == nil {
		r.Mail = make(map[int64]*Mail)
	}
	if r.MailLog == nil {
		r.MailLog = make(map[int64]*MailLog)
	}

}

func SetFuncOpenDefaults(r *FuncOpen) {
	if r == nil {
		return
	}
	if r.UnlockList == nil {
		r.UnlockList = make(map[int32]int64)
	}

}

func SetMonsterCollectItemDefaults(r *MonsterCollectItem) {
	if r == nil {
		return
	}

}

func SetMonsterCollectDefaults(r *MonsterCollect) {
	if r == nil {
		return
	}
	if r.CollectList == nil {
		r.CollectList = make([]*MonsterCollectItem, 0)
	}

}

func SetRoleOpRecordDefaults(r *RoleOpRecord) {
	if r == nil {
		return
	}

}

func SetBattlePassDefaults(r *BattlePass) {
	if r == nil {
		return
	}
	if r.GotStatus == nil {
		r.GotStatus = make(map[int32]int32)
	}

}

func SetVipChargeLogDefaults(r *VipChargeLog) {
	if r == nil {
		return
	}

}

func SetLogInfoDefaults(r *LogInfo) {
	if r == nil {
		return
	}
	if r.QuestionnaireRewardLog == nil {
		r.QuestionnaireRewardLog = make(map[string]*QuestionnaireRewardLog)
	}
	if r.DrawGachaLog == nil {
		r.DrawGachaLog = make(map[int32]*DrawGachaLog)
	}
	if r.VipChargeLog == nil {
		r.VipChargeLog = make(map[int32]*VipChargeLog)
	}
	if r.AdViewLog == nil {
		r.AdViewLog = make(map[int32]*AdViewLog)
	}
	if r.RedeemCodeLog == nil {
		r.RedeemCodeLog = make([]*RedeemCodeLog, 0)
	}

}

func SetQuestionnaireRewardLogDefaults(r *QuestionnaireRewardLog) {
	if r == nil {
		return
	}
	if r.Rewards == nil {
		r.Rewards = make([]*RoleItemChangeDto, 0)
	}

}

func SetFeedbackLogDefaults(r *FeedbackLog) {
	if r == nil {
		return
	}
	if r.Rewards == nil {
		r.Rewards = make([]*RoleItemChangeDto, 0)
	}

}

func SetFeedbackLogInfoDefaults(r *FeedbackLogInfo) {
	if r == nil {
		return
	}
	if r.FeedbackLog == nil {
		r.FeedbackLog = make([]*FeedbackLog, 0)
	}

}

func SetUavDefaults(r *Uav) {
	if r == nil {
		return
	}

}

func SetUavFormationDefaults(r *UavFormation) {
	if r == nil {
		return
	}
	if r.Formation == nil {
		r.Formation = make(map[int32]int32)
	}

}

func SetUavSlotItemDefaults(r *UavSlotItem) {
	if r == nil {
		return
	}

}

func SetUavSlotsDefaults(r *UavSlots) {
	if r == nil {
		return
	}
	if r.Slots == nil {
		r.Slots = make(map[int32]*UavSlotItem)
	}

}

func SetUavInfoDefaults(r *UavInfo) {
	if r == nil {
		return
	}
	if r.Uav == nil {
		r.Uav = make(map[int32]*Uav)
	}
	if r.UavFormation == nil {
		r.UavFormation = &UavFormation{}
		SetUavFormationDefaults(r.UavFormation)
	}
	if r.UavSlots == nil {
		r.UavSlots = &UavSlots{}
		SetUavSlotsDefaults(r.UavSlots)
	}

}

func SetWeaponSkinWearDefaults(r *WeaponSkinWear) {
	if r == nil {
		return
	}

}

func SetWeaponSkinDefaults(r *WeaponSkin) {
	if r == nil {
		return
	}

}

func SetWeaponInfoDefaults(r *WeaponInfo) {
	if r == nil {
		return
	}
	if r.WeaponSkinWear == nil {
		r.WeaponSkinWear = &WeaponSkinWear{}
		SetWeaponSkinWearDefaults(r.WeaponSkinWear)
	}
	if r.WeaponSkin == nil {
		r.WeaponSkin = make(map[int32]*WeaponSkin)
	}

}

func SetAfkEarningsDefaults(r *AfkEarnings) {
	if r == nil {
		return
	}
	if r.LastLeftItem == nil {
		r.LastLeftItem = make(map[int32]float64)
	}

}

func SetBadgeRedPointDefaults(r *BadgeRedPoint) {
	if r == nil {
		return
	}

}

func SetBadgeInfoDefaults(r *BadgeInfo) {
	if r == nil {
		return
	}
	if r.RedPointList == nil {
		r.RedPointList = make([]*BadgeRedPoint, 0)
	}

}

func SetRenovationLaboratoryDefaults(r *RenovationLaboratory) {
	if r == nil {
		return
	}
	if r.UnlockedSkillId == nil {
		r.UnlockedSkillId = make([]int32, 0)
	}

}

func SetMttCbtTicketRewardDefaults(r *MttCbtTicketReward) {
	if r == nil {
		return
	}

}

func SetRedeemCodeLogDefaults(r *RedeemCodeLog) {
	if r == nil {
		return
	}

}

func SetAdViewLogDefaults(r *AdViewLog) {
	if r == nil {
		return
	}

}

func SetCombatAntiCheatingDefaults(r *CombatAntiCheating) {
	if r == nil {
		return
	}

}

func SetAntiCheatingInfoDefaults(r *AntiCheatingInfo) {
	if r == nil {
		return
	}
	if r.AntiCheatingList == nil {
		r.AntiCheatingList = make([]*CombatAntiCheating, 0)
	}

}

func SetRoleBaseInfoDefaults(r *RoleBaseInfo) {
	if r == nil {
		return
	}

}

func SetItemInfoDefaults(r *ItemInfo) {
	if r == nil {
		return
	}
	if r.Items == nil {
		r.Items = make(map[int32]*Item)
	}

}
