// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tables_tags.proto

package pbtest

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// oneof_tags 演示（EX-SC-006，非表消息，供 -mode=tag 验证）。
type TagExample struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WithTags string                 `protobuf:"bytes,1,opt,name=with_tags,json=withTags,proto3" json:"with_tags,omitempty"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*TagExample_A
	//	*TagExample_B
	OneOf         isTagExample_OneOf `protobuf_oneof:"one_of"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagExample) Reset() {
	*x = TagExample{}
	mi := &file_tables_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagExample) ProtoMessage() {}

func (x *TagExample) ProtoReflect() protoreflect.Message {
	mi := &file_tables_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagExample.ProtoReflect.Descriptor instead.
func (*TagExample) Descriptor() ([]byte, []int) {
	return file_tables_tags_proto_rawDescGZIP(), []int{0}
}

func (x *TagExample) GetWithTags() string {
	if x != nil {
		return x.WithTags
	}
	return ""
}

func (x *TagExample) GetOneOf() isTagExample_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *TagExample) GetA() string {
	if x != nil {
		if x, ok := x.OneOf.(*TagExample_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *TagExample) GetB() int32 {
	if x != nil {
		if x, ok := x.OneOf.(*TagExample_B); ok {
			return x.B
		}
	}
	return 0
}

type isTagExample_OneOf interface {
	isTagExample_OneOf()
}

type TagExample_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof"`
}

type TagExample_B struct {
	B int32 `protobuf:"varint,6,opt,name=b,proto3,oneof"`
}

func (*TagExample_A) isTagExample_OneOf() {}

func (*TagExample_B) isTagExample_OneOf() {}

var File_tables_tags_proto protoreflect.FileDescriptor

const file_tables_tags_proto_rawDesc = "" +
	"\n" +
	"\x11tables_tags.proto\x12\x06pbtest\x1a\x10orm.option.proto\"\x9a\x01\n" +
	"\n" +
	"TagExample\x121\n" +
	"\twith_tags\x18\x01 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"withTags\"R\bwithTags\x12\x1d\n" +
	"\x01a\x18\x05 \x01(\tB\r\x9a\x84\x9e\x03\bjson:\"A\"H\x00R\x01a\x12\x1d\n" +
	"\x01b\x18\x06 \x01(\x05B\r\x9a\x84\x9e\x03\bjson:\"b\"H\x00R\x01bB\x1b\n" +
	"\x06one_of\x12\x11\x9a\x84\x9e\x03\fjson:\"oneOf\"B\vZ\tgs/pbtestb\x06proto3"

var (
	file_tables_tags_proto_rawDescOnce sync.Once
	file_tables_tags_proto_rawDescData []byte
)

func file_tables_tags_proto_rawDescGZIP() []byte {
	file_tables_tags_proto_rawDescOnce.Do(func() {
		file_tables_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tables_tags_proto_rawDesc), len(file_tables_tags_proto_rawDesc)))
	})
	return file_tables_tags_proto_rawDescData
}

var file_tables_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tables_tags_proto_goTypes = []any{
	(*TagExample)(nil), // 0: pbtest.TagExample
}
var file_tables_tags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tables_tags_proto_init() }
func file_tables_tags_proto_init() {
	if File_tables_tags_proto != nil {
		return
	}
	file_tables_tags_proto_msgTypes[0].OneofWrappers = []any{
		(*TagExample_A)(nil),
		(*TagExample_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tables_tags_proto_rawDesc), len(file_tables_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tables_tags_proto_goTypes,
		DependencyIndexes: file_tables_tags_proto_depIdxs,
		MessageInfos:      file_tables_tags_proto_msgTypes,
	}.Build()
	File_tables_tags_proto = out.File
	file_tables_tags_proto_goTypes = nil
	file_tables_tags_proto_depIdxs = nil
}
