// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: version_player.proto
// time 2026-06-04

package pbtest

import (
	proto "google.golang.org/protobuf/proto"
)

// GetVersionedPlayerTable 转换actor state为VersionedPlayer类型
func GetVersionedPlayerTable(holder interface{ GetStateValue() proto.Message }) *VersionedPlayer {
	return holder.GetStateValue().(*VersionedPlayer)
}

// SetVersion 设置VersionedPlayer的版本号
func (x *VersionedPlayer) SetVersion(ver int64) {
	if x == nil {
		return
	}
	x.Version = ver
}

func SetVersionedPlayerDefaults(r *VersionedPlayer) {
	if r == nil {
		return
	}

}
