// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: version_player.proto

package pbtest

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 玩家数据 ====================
type VersionedPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Version       int64                  `protobuf:"varint,28,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedPlayer) Reset() {
	*x = VersionedPlayer{}
	mi := &file_version_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedPlayer) ProtoMessage() {}

func (x *VersionedPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_version_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedPlayer.ProtoReflect.Descriptor instead.
func (*VersionedPlayer) Descriptor() ([]byte, []int) {
	return file_version_player_proto_rawDescGZIP(), []int{0}
}

func (x *VersionedPlayer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VersionedPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VersionedPlayer) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VersionedPlayer) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *VersionedPlayer) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_version_player_proto protoreflect.FileDescriptor

const file_version_player_proto_rawDesc = "" +
	"\n" +
	"\x14version_player.proto\x12\x06pbtest\x1a\x10orm.option.proto\"\x92\x01\n" +
	"\x0fVersionedPlayer\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xa0\x84\x9e\x03\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\aversion\x18\x1c \x01(\x03R\aversion:\f\xf0\xa7\x1d\x01\xfa\xa7\x1d\x04gameB\vZ\tgs/pbtestb\x06proto3"

var (
	file_version_player_proto_rawDescOnce sync.Once
	file_version_player_proto_rawDescData []byte
)

func file_version_player_proto_rawDescGZIP() []byte {
	file_version_player_proto_rawDescOnce.Do(func() {
		file_version_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_player_proto_rawDesc), len(file_version_player_proto_rawDesc)))
	})
	return file_version_player_proto_rawDescData
}

var file_version_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_version_player_proto_goTypes = []any{
	(*VersionedPlayer)(nil), // 0: pbtest.VersionedPlayer
}
var file_version_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_version_player_proto_init() }
func file_version_player_proto_init() {
	if File_version_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_player_proto_rawDesc), len(file_version_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_version_player_proto_goTypes,
		DependencyIndexes: file_version_player_proto_depIdxs,
		MessageInfos:      file_version_player_proto_msgTypes,
	}.Build()
	File_version_player_proto = out.File
	file_version_player_proto_goTypes = nil
	file_version_player_proto_depIdxs = nil
}
