// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           tcaplus
// source: tables.proto
// time 2026-06-04

package tcaplus

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "gs/pbtest"

// methods for pbtest.Player in tcaplus

func (m *Player) TableName() string {
	return "player" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *Player) NewValue() proto.Message {
	return &pbtest.Player{}
}

func (m *Player) PrimaryKey() []any {
	return []any{m.Id}
}

func (m *Player) PrimaryKeyNames() []string {
	return []string{
		"id",
	}
}

func (m *Player) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.Id) {
		ret["id"] = m.Id
	}

	return ret
}

func (m *Player) ToPrimaryKeyStruct() any {
	s := &Player{}

	if !m.isZeroValue(m.Id) {
		s.Id = m.Id
	}

	return s
}

func (m *Player) Indexes() []any {
	return []any{m.Name, m.Level}
}

func (m *Player) IndexNames() []string {
	return []string{"name", "level"}
}

func (m *Player) ToIndexMap() map[string]any {
	ret := map[string]any{}

	if !m.isZeroValue(m.Name) {
		ret["name"] = m.Name
	}
	if !m.isZeroValue(m.Level) {
		ret["level"] = m.Level
	}

	return ret
}

func (m *Player) ToIndexStruct() any {
	s := &Player{}

	if !m.isZeroValue(m.Name) {
		s.Name = m.Name
	}
	if !m.isZeroValue(m.Level) {
		s.Level = m.Level
	}

	return s
}

func (m *Player) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *Player) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *Player) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*pbtest.Player)
	m.Id = r.Id // set pk

	m.Name = r.Name // set index

	m.Level = r.Level // set index

	d, err := proto.Marshal(value)
	if err != nil {
		return err
	}
	m.Data = d

	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *Player) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *Player) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	err := proto.Unmarshal(m.Data, value)
	if err != nil {
		return err
	}

	pbtest.SetPlayerDefaults(value.(*pbtest.Player))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}
