// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: version_player.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tca_version_player.proto

package tcaplus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tcaplus表结构定义
type VersionedPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,28,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,999,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,1000,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,1001,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedPlayer) Reset() {
	*x = VersionedPlayer{}
	mi := &file_tca_version_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedPlayer) ProtoMessage() {}

func (x *VersionedPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_tca_version_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedPlayer.ProtoReflect.Descriptor instead.
func (*VersionedPlayer) Descriptor() ([]byte, []int) {
	return file_tca_version_player_proto_rawDescGZIP(), []int{0}
}

func (x *VersionedPlayer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VersionedPlayer) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionedPlayer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VersionedPlayer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VersionedPlayer) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_tca_version_player_proto protoreflect.FileDescriptor

const file_tca_version_player_proto_rawDesc = "" +
	"\n" +
	"\x18tca_version_player.proto\x12\atcaplus\x1a\x1dtcaplusservice.optionv1.proto\"\x98\x01\n" +
	"\x0fVersionedPlayer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aversion\x18\x1c \x01(\x03R\aversion\x12\x13\n" +
	"\x04data\x18\xe7\a \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"created_at\x18\xe8\a \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"updated_at\x18\xe9\a \x01(\x03R\tupdatedAt:\x06\x82\xa6\x1d\x02idB\x19Z\x17pbtest/internal/tcaplusb\x06proto3"

var (
	file_tca_version_player_proto_rawDescOnce sync.Once
	file_tca_version_player_proto_rawDescData []byte
)

func file_tca_version_player_proto_rawDescGZIP() []byte {
	file_tca_version_player_proto_rawDescOnce.Do(func() {
		file_tca_version_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tca_version_player_proto_rawDesc), len(file_tca_version_player_proto_rawDesc)))
	})
	return file_tca_version_player_proto_rawDescData
}

var file_tca_version_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tca_version_player_proto_goTypes = []any{
	(*VersionedPlayer)(nil), // 0: tcaplus.VersionedPlayer
}
var file_tca_version_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tca_version_player_proto_init() }
func file_tca_version_player_proto_init() {
	if File_tca_version_player_proto != nil {
		return
	}
	file_tcaplusservice_optionv1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tca_version_player_proto_rawDesc), len(file_tca_version_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tca_version_player_proto_goTypes,
		DependencyIndexes: file_tca_version_player_proto_depIdxs,
		MessageInfos:      file_tca_version_player_proto_msgTypes,
	}.Build()
	File_tca_version_player_proto = out.File
	file_tca_version_player_proto_goTypes = nil
	file_tca_version_player_proto_depIdxs = nil
}
