// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           mysql
// source: tables_tags.proto
// time 2026-06-06

package mysql
