// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: tables_tags.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_tables_tags.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MySQL表结构定义
type TagExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithTags      string                 `protobuf:"bytes,1,opt,name=with_tags,json=withTags,proto3" json:"with_tags,omitempty"` //{ "origin":"with_tags" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagExample) Reset() {
	*x = TagExample{}
	mi := &file_tb_tables_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagExample) ProtoMessage() {}

func (x *TagExample) ProtoReflect() protoreflect.Message {
	mi := &file_tb_tables_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagExample.ProtoReflect.Descriptor instead.
func (*TagExample) Descriptor() ([]byte, []int) {
	return file_tb_tables_tags_proto_rawDescGZIP(), []int{0}
}

func (x *TagExample) GetWithTags() string {
	if x != nil {
		return x.WithTags
	}
	return ""
}

var File_tb_tables_tags_proto protoreflect.FileDescriptor

const file_tb_tables_tags_proto_rawDesc = "" +
	"\n" +
	"\x14tb_tables_tags.proto\x12\x05mysql\")\n" +
	"\n" +
	"TagExample\x12\x1b\n" +
	"\twith_tags\x18\x01 \x01(\tR\bwithTagsB\x1aZ\x18gs/pbtest/internal/mysqlb\x06proto3"

var (
	file_tb_tables_tags_proto_rawDescOnce sync.Once
	file_tb_tables_tags_proto_rawDescData []byte
)

func file_tb_tables_tags_proto_rawDescGZIP() []byte {
	file_tb_tables_tags_proto_rawDescOnce.Do(func() {
		file_tb_tables_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_tables_tags_proto_rawDesc), len(file_tb_tables_tags_proto_rawDesc)))
	})
	return file_tb_tables_tags_proto_rawDescData
}

var file_tb_tables_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tb_tables_tags_proto_goTypes = []any{
	(*TagExample)(nil), // 0: mysql.TagExample
}
var file_tb_tables_tags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tb_tables_tags_proto_init() }
func file_tb_tables_tags_proto_init() {
	if File_tb_tables_tags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_tables_tags_proto_rawDesc), len(file_tb_tables_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_tables_tags_proto_goTypes,
		DependencyIndexes: file_tb_tables_tags_proto_depIdxs,
		MessageInfos:      file_tb_tables_tags_proto_msgTypes,
	}.Build()
	File_tb_tables_tags_proto = out.File
	file_tb_tables_tags_proto_goTypes = nil
	file_tb_tables_tags_proto_depIdxs = nil
}
