// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           mysql
// source: version_player.proto
// time 2026-06-06

package mysql

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "gs/pbtest"

// methods for pbtest.VersionedPlayer in mysql

func (m *VersionedPlayer) TableName() string {
	return "versioned_player" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *VersionedPlayer) NewValue() proto.Message {
	return &pbtest.VersionedPlayer{}
}

func (m *VersionedPlayer) PrimaryKey() []any {
	return []any{m.Id}
}

func (m *VersionedPlayer) PrimaryKeyNames() []string {
	return []string{
		"id",
	}
}

func (m *VersionedPlayer) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.Id) {
		ret["id"] = m.Id
	}

	return ret
}

func (m *VersionedPlayer) ToPrimaryKeyStruct() any {
	s := &VersionedPlayer{}

	if !m.isZeroValue(m.Id) {
		s.Id = m.Id
	}

	return s
}

func (m *VersionedPlayer) Indexes() []any {
	return []any{}
}

func (m *VersionedPlayer) IndexNames() []string {
	return []string{}
}

func (m *VersionedPlayer) ToIndexMap() map[string]any {
	ret := map[string]any{}

	return ret
}

func (m *VersionedPlayer) ToIndexStruct() any {
	s := &VersionedPlayer{}

	return s
}

func (m *VersionedPlayer) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *VersionedPlayer) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *VersionedPlayer) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*pbtest.VersionedPlayer)
	m.Id = r.Id // set pk

	d, err := proto.Marshal(value)
	if err != nil {
		return err
	}
	m.Data = d
	vp := value.(interface {
		GetVersion() int64
	})
	m.Version = vp.GetVersion()
	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *VersionedPlayer) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *VersionedPlayer) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	err := proto.Unmarshal(m.Data, value)
	if err != nil {
		return err
	}
	vp := value.(interface {
		SetVersion(ver int64)
	})
	vp.SetVersion(m.Version)
	pbtest.SetVersionedPlayerDefaults(value.(*pbtest.VersionedPlayer))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

// SetVersion 设置VersionedPlayer的版本号
func (m *VersionedPlayer) SetVersion(ver int64) {
	if m == nil {
		return
	}
	m.Version = ver
}
